# Generated by Django 3.0.8 on 2020-07-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0002_auto_20200709_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_code',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
