# Generated by Django 3.0.3 on 2020-07-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0004_auto_20200719_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_access',
            field=models.BooleanField(default=False),
        ),
    ]
