# Generated by Django 3.0.3 on 2020-08-07 07:57

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0005_profile_full_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='strike',
            field=django_mysql.models.ListTextField(models.IntegerField(), null=True, size=4),
        ),
    ]
