# Generated by Django 3.0.3 on 2020-08-07 15:54

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0006_answer_strike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='strike',
        ),
        migrations.CreateModel(
            name='Strike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strike', django_mysql.models.ListTextField(models.IntegerField(), null=True, size=4)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaksh.Question')),
            ],
        ),
        migrations.AddField(
            model_name='answerpaper',
            name='strikes',
            field=models.ManyToManyField(to='yaksh.Strike'),
        ),
    ]
