# Generated by Django 3.0.3 on 2020-08-10 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0007_auto_20200807_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='discount',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_default_discount',
            field=models.BooleanField(default=True),
        ),
    ]
