# Generated by Django 3.0.3 on 2020-08-10 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0008_auto_20200810_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodule',
            name='discount',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
