# Generated by Django 3.0.3 on 2020-08-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0009_learningmodule_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodule',
            name='apply_to_all_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
