# Generated by Django 3.0.3 on 2020-07-06 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(default='About the grading system!')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GradeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_limit', models.FloatField()),
                ('upper_limit', models.FloatField()),
                ('grade', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=127, null=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.GradingSystem')),
            ],
        ),
    ]
