# Generated by Django 3.0.8 on 2020-07-14 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('letsprepare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availablequizzes',
            old_name='transaction_id',
            new_name='TXNID',
        ),
        migrations.AddField(
            model_name='availablequizzes',
            name='successful',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PaytmHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MID', models.CharField(max_length=40)),
                ('TXNID', models.CharField(default='TRIAL', max_length=255)),
                ('ORDERID', models.CharField(max_length=30, verbose_name='ORDER ID')),
                ('BANKTXNID', models.IntegerField(blank=True, null=True, verbose_name='BANK TXN ID')),
                ('TXNAMOUNT', models.FloatField(verbose_name='TXN AMOUNT')),
                ('CURRENCY', models.CharField(blank=True, max_length=4, null=True, verbose_name='CURRENCY')),
                ('STATUS', models.CharField(max_length=12, verbose_name='STATUS')),
                ('RESPCODE', models.IntegerField(verbose_name='RESP CODE')),
                ('RESPMSG', models.TextField(max_length=250, verbose_name='RESP MSG')),
                ('TXNDATE', models.DateTimeField(default=django.utils.timezone.now, verbose_name='TXN DATE')),
                ('GATEWAYNAME', models.CharField(blank=True, max_length=30, null=True, verbose_name='GATEWAY NAME')),
                ('BANKNAME', models.CharField(blank=True, max_length=50, null=True, verbose_name='BANK NAME')),
                ('PAYMENTMODE', models.CharField(blank=True, max_length=10, null=True, verbose_name='PAYMENT MODE')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
