# Generated by Django 3.0.8 on 2020-07-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsprepare', '0002_auto_20200714_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availablequizzes',
            old_name='TXNID',
            new_name='order_id',
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='TXNID',
            field=models.IntegerField(verbose_name='TXNID'),
        ),
    ]
