# Generated by Django 3.0.8 on 2020-07-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsprepare', '0003_auto_20200714_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytmhistory',
            name='BANKTXNID',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='BANK TXN ID'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='RESPCODE',
            field=models.CharField(max_length=30, verbose_name='RESP CODE'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='RESPMSG',
            field=models.CharField(max_length=250, verbose_name='RESP MSG'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='TXNAMOUNT',
            field=models.CharField(max_length=30, verbose_name='TXN AMOUNT'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='TXNDATE',
            field=models.CharField(default='NOW', max_length=30, verbose_name='TXN DATE'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='TXNID',
            field=models.CharField(max_length=30, verbose_name='TXNID'),
        ),
    ]
