# Generated by Django 3.0.8 on 2020-07-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsprepare', '0004_auto_20200714_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytmhistory',
            name='BANKTXNID',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='BANK TXN ID'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='GATEWAYNAME',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GATEWAY NAME'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='ORDERID',
            field=models.CharField(max_length=100, verbose_name='ORDER ID'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='RESPCODE',
            field=models.CharField(max_length=100, verbose_name='RESP CODE'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='TXNAMOUNT',
            field=models.CharField(max_length=100, verbose_name='TXN AMOUNT'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='TXNDATE',
            field=models.CharField(default='NOW', max_length=100, verbose_name='TXN DATE'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='TXNID',
            field=models.CharField(max_length=100, verbose_name='TXNID'),
        ),
    ]
